// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOCetwsnPsL4ovsaoRGROOWGZS57yVNhI',
    appId: '1:58738058163:web:7001d3619922b8e66761c6',
    messagingSenderId: '58738058163',
    projectId: 'verifyu-24',
    authDomain: 'verifyu-24.firebaseapp.com',
    storageBucket: 'verifyu-24.firebasestorage.app',
    measurementId: 'G-HXMNDD5XJY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6Tds08JhUjcocciIWXV3g3FyNQRCzdR4',
    appId: '1:58738058163:android:60e2bacfc3a9bc056761c6',
    messagingSenderId: '58738058163',
    projectId: 'verifyu-24',
    storageBucket: 'verifyu-24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy2ABjDk-O2Q_sLfIbCJlKn-GTBe_DM9Y',
    appId: '1:58738058163:ios:1739e15c48b493bf6761c6',
    messagingSenderId: '58738058163',
    projectId: 'verifyu-24',
    storageBucket: 'verifyu-24.firebasestorage.app',
    iosBundleId: 'com.example.verifyu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy2ABjDk-O2Q_sLfIbCJlKn-GTBe_DM9Y',
    appId: '1:58738058163:ios:1739e15c48b493bf6761c6',
    messagingSenderId: '58738058163',
    projectId: 'verifyu-24',
    storageBucket: 'verifyu-24.firebasestorage.app',
    iosBundleId: 'com.example.verifyu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOCetwsnPsL4ovsaoRGROOWGZS57yVNhI',
    appId: '1:58738058163:web:b3099c409af1f1566761c6',
    messagingSenderId: '58738058163',
    projectId: 'verifyu-24',
    authDomain: 'verifyu-24.firebaseapp.com',
    storageBucket: 'verifyu-24.firebasestorage.app',
    measurementId: 'G-VVGZ1VWQLN',
  );
}
